config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  namespace :admin do
    get "homes/top" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :reviews, only: [:index, :show, :destroy]
    get "search_tag" => "reviews#search_tag"
  end

  scope module: :public do
    get "homes/top"
    get "homes/about"

    resources :reviews, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :pickups, only: [:create, :destroy]
      resources :stars, only: [:create, :destroy]
      get "/review/hashtag/:name" => "reviews#hashtag"
      get "/review/hashtag" => "reviews#hashtag"
      resources :comments, only: [:create, :destroy]
      collection do
        get "search"
      end
    end

    resources :users, only: [:show, :edit, :update, :friends, :destroy] do
      get "unsubscribe"
      member do
        get :pickups
      end
      # フォロー機能はuserにネストさせている
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

    get "search_tag" => "reviews#search_tag"
    resources :follows, only: [:create, :destroy]
    resources :notifications, only: [:index]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 追加
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :password, length: { maximum: 75 }

  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :pickups, dependent: :destroy
  has_many :pickuped_reviews, through: :pickups, source: :review
  # has_many :notifications, dependent: :destroy

  # follower_id=自分
  # follow_id=相手
  # 自分がフォローしたり、アンフォローしたりするための記述
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # sourceは本当はfollow_idとなっていてカラム名を示している。
  # フォロー一覧を表示するための記述
  has_many :followings, through: :relationships, source: :follow

  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  # フォロワー一覧を表示するための記述
  has_many :followers, through: :reverse_relationships, source: :follower

  def follow(user_id)
    relationships.create(follow_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # pickupsテーブルにreview_idが存在しているかどうか検索をかけている
  def pickuped_by?(review_id)
    pickups.where(review_id: review_id).exists?
  end

  # ゲストログイン機能で追加
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.introduction = "ゲストユーザーです。"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているため，user.name = "ゲストユーザー"
    end
  end

  has_one_attached :user_image

  # ログイン時にemail/nameでできるようにした際に追加
  # def login
  #   @login || self.name || self.email
  # end

  # def self.find_for_database_authentication(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if (login = conditions.delete(:login))
  #     where(conditions.to_h).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  #   elsif conditions.has_key?(:name) || conditions.has_key?(:email)
  #     where(conditions.to_h).first
  #   end
  # end

  # def validate_name
  #   if User.where(email: name).exists?
  #     errors.add(:name, :invalid)
  #   end
  # end

  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      user_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    user_image.variant(resize_to_limit: [width, height]).processed
  end

  # ユーザー名が3文字未満の場合はエラーを出すようにしたいが
  # TerminalでArugument Error（引数エラー）が発生する　↓
  # validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_homes_top_path
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<!-- ユーザー一覧 admin/users/index -->

<div class="col-md-8">
  <h5 class="mb-4">admin / ユーザー一覧</h5>
</div>

<!-- ユーザー一覧 -->
<div class="row">
  <div class="col-md-8">
    <% @users.each do |user| %>
      <div class="d-flex mb-1">
        <div>
          <%= link_to admin_user_path(user.id), class: 'text-dark' do %>
            <%= image_tag user.get_user_image(70,70) %>
          <% end %>
        </div>

        <div>
          <p><%= link_to "#{user.name}", admin_user_path(user.id), class: 'text-dark' %></p>
          <p><%= link_to "#{user.introduction}".truncate(25, omission: '...'), admin_user_path(user.id), class: 'text-dark' %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<!-- admin/users/show ユーザー詳細ページ -->

<!-- プロフィール欄 -->
<div class="col">
  <div class="row">
    <div class="mx-3">
      <%= image_tag @user.get_user_image(140,140) %>
    </div>

    <div class="col "><!-- プロフィール内容 -->
      <div class="d-flex align-items-center mb-2">
        <%= @user.name %>
        <%= link_to "アカウントを削除", admin_user_path(@user.id), method: :delete, "data-confirm" => "本当にユーザーを削除しますか？", class: 'ml-5 btn btn-outline-danger' %>
      </div>

      <div class="d-flex">
        <p class="mr-5">投稿数：<%= @reviews.count %></p>
        <p class="mr-3"><%= link_to "#{@user.followings.count}フォロー中", admin_user_followings_path(@user.id), class: 'text-dark' %></p>
        <p><%= link_to "#{@user.followers.count}フォロワー", admin_user_followers_path(@user.id), class: 'text-dark' %></p>
      </div>

      <div>
        <p><%= @user.introduction %></p>
      </div>
    </div><!-- /プロフィール内容 -->
  </div><!-- /row　/プロフィール欄 -->
</div><!-- /col -->

<!-- ユーザーの投稿一覧 -->
<div class="m-3">
  <div class="row justify-content-start">
    <% @reviews.each do |review| %>
      <div class="card mb-4 mx-auto" style="width: 23rem;" preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
        <div>
          <!-- ゆくゆくは画像の複数枚投稿・表示させたい -->
          <%= link_to admin_user_path(review.user.id), class: 'text-dark' do %>
            <%= image_tag review.user.get_user_image(30,30), class: 'm-2' %>
            <%= review.user.name %>
          <% end %>
        </div>

        <%= link_to admin_review_path(review.id) do %>
          <%= image_tag review.get_review_image(500,500), class: 'bd-placeholder-img card-img-top', style: 'width: 100%; height: 150px; object-fit: cover;' %>
        <% end %>

        <div class="d-flex mt-1">
          <!-- レビューの平均 -->
          <div class="starrate ml-3 mr-5 d-flex">
            <%# 評価数を星に置き換える %>
            <div id="average-review-rating-<%= review.id %>" data-score=<%= review.average_rating %> class="mr-3"></div>
            <div class="my-auto"><%= review.average_rating %></div>
          </div>

          <!-- Pickup（いいね） -->
          <div id = "pickup_<%= review.id %>", class="mt-1">
            <%= render partial: "public/homes/pickup", locals: { review: review } %>
          </div>
        </div>

        <!-- 投稿本文 -->
        <div class="mx-3">
          <div class="mt-2 mb-1">
            <span class="font-weight-bold"><%= review.title %></span>
          </div>
          <!--タグリスト-->
          <div class="my-1">
            <% review.hashtags.each do |list|%>
              <%= link_to "##{list.name}", admin_search_tag_path(hashtag_id: list.id) %>
            <% end %>
          </div>

          <div class="my-1 mb-2">
            <input id="trigger<%= review.id %>" class="grad-trigger" type="checkbox">
            <label class="grad-btn text-muted" for="trigger<%= review.id %>" type="review_id">続きを読む</label>
            <div class="grad-item"><%= review.body %></div>
          </div>
        </div>

        <!--コメント一覧部分-->
        <div id="comments_area">
          <ul class="list_none">
            <% if review.comments.present? %>
              <li>最新のコメント2件を表示</li>
            <% end %>
            <% review.comments.first(2). each do |comment| %>
              <li>
                <%= image_tag comment.user.get_user_image(20,20) %>
                <%= comment.comment %>
              </li>
            <% end %>
            <% if review.comments.present? %>
              <li>
                <button type="button" class="button" data-toggle="modal" data-target="#exampleModalLong<%= review.id %>">
                  <span class="text-secondary">...コメント<%= review.comments.count %>件を全て表示</span>
                </button>
              </li>
            <% end %>
          </ul>

          <div class="modal fade" id="exampleModalLong<%= review.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= render 'public/comments/comments', review: review %>
                </div>
              </div>
            </div>
          </div>

        </div><!-- /comments_area -->
      </div><!-- /card -->
    <% end %><!-- review.eachのend -->
  </div><!-- /row カードの2行横並べ -->
</div><!-- /col -->

<script>
  // jquery発火イベントを記載
  <% @reviews.each do |review| %>
    $('#average-review-rating-<%= review.id %>').empty();
    var elem = document.getElementById('average-review-rating-<%=review.id%>');
    var opt = {
        readOnly: true,
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: function() {
           return $(this).attr('data-score')
        }
    }
    raty(elem, opt);
  <% end %>
</script>

<style>
  .button {
    border: none;
    outline: none;
    background: transparent;
  }

  .list_none {
    list-style: none;
  }

  /* 以下、「続きを見る」ボタン */
  .grad-item {
    position: relative;
    overflow: hidden;
    height: 35px; /*隠した状態の高さ*/
  }
  .grad-item::before {
    display: block;
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 40px; /*グラデーションで隠す高さ*/
    background: -webkit-linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 50%, rgba(255,255,255,0.9) 50%, #fff 100%);
    background: linear-gradient(top, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 50%, rgba(255,255,255,0.9) 50%, #fff 100%);
    content: "";
  }
  .grad-trigger {
    display: none; /*チェックボックスは常に非表示*/
  }
  .grad-trigger:checked + .grad-btn {
    display: none; /*チェックされていたら、grad-btnを非表示にする*/
  }
  .grad-trigger:checked ~ .grad-item {
    height: auto; /*チェックされていたら、高さを戻す*/
  }
  .grad-trigger:checked ~ .grad-item::before {
    display: none; /*チェックされていたら、grad-itemのbeforeを非表示にする*/
  }
</style>