config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  namespace :admin do
    get "homes/top" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :reviews, only: [:index, :show, :destroy]
    get "search_tag" => "reviews#search_tag"
  end

  scope module: :public do
    get "homes/top"
    get "homes/about"

    resources :reviews, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :pickups, only: [:create, :destroy]
      resources :stars, only: [:create, :destroy]
      get "/review/hashtag/:name" => "reviews#hashtag"
      get "/review/hashtag" => "reviews#hashtag"
      resources :comments, only: [:create, :destroy]
      collection do
        get "search"
      end
    end

    resources :users, only: [:show, :edit, :update, :friends, :destroy] do
      get "unsubscribe"
      member do
        get :pickups
      end
      # フォロー機能はuserにネストさせている
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

    get "search_tag" => "reviews#search_tag"
    resources :follows, only: [:create, :destroy]
    resources :notifications, only: [:index]
  end
end

app/views/layouts/_error_messages.html.erb
<!--エラーメッセージ-->
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <h3><%= model.errors.count %>件のエラーが発生しています。</h3>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourBoarders</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

    <script src="https://kit.fontawesome.com/e8f9341ad1.js" crossorigin="anonymous"></script>
    <!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row mx-auto">
        <div class="col-md-3 mt-4">
          <header>
            <nav class="navbar navbar-expand-lg navbar-light flex-column">
              <!-- /admin ログイン時のheader -->
              <% if admin_signed_in? %>
                <%= link_to admin_homes_top_path, class: 'navbar-brand font-weight-bold pb-4' do %>
                  <%= image_tag 'logo.jpg', size: "170x30" %>
                <% end %>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav ml-auto flex-column">
                    <li class="nav-item">
                      <%= link_to admin_homes_top_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-house pr-2 fa-lg"></i>ホーム
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to admin_reviews_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-magnifying-glass pr-2 fa-lg"></i>投稿検索
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to admin_users_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-users pr-2 fa-lg"></i>ユーザー一覧
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark my-1' do %>
                        <i class="fa-solid fa-arrow-right-from-bracket pr-2 fa-lg"></i>ログアウト
                      <% end %>
                    </li>
                  </ul>
                </div>

              <!-- /user ログイン時のheader -->
              <% elsif user_signed_in? %>
                <%= link_to homes_top_path, class: 'navbar-brand font-weight-bold pb-4' do %>
                  <%= image_tag 'logo.jpg', size: "170x30" %>
                <% end %>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav ml-auto flex-column">
                    <li class="nav-item">
                      <%= link_to homes_top_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-house pr-2 fa-lg"></i>ホーム
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to reviews_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-magnifying-glass pr-2 fa-lg"></i>トピック検索
                      <% end %>
                    </li>
                    <!--<li class="nav-item">-->
                    <!--  <%#= link_to notifications_path, class: 'nav-link text-dark mr-3' do %>-->
                        <!--<i class="fa-solid fa-bell pr-2"></i>通知-->
                    <!--  <%# end %>-->
                    <!--</li>-->
                    <li class="nav-item">
                      <%= link_to pickups_user_path(current_user.id), class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-bookmark pr-2 fa-lg"></i>Pick Up
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to user_path(current_user.id), class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-user pr-2 fa-lg"></i>プロフィール
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to new_review_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-regular fa-square-plus pr-2 fa-lg"></i>投稿する
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark my-1' do %>
                        <i class="fa-solid fa-arrow-right-from-bracket pr-2 fa-lg"></i>ログアウト
                      <% end %>
                    </li>
                  </ul>
                </div>

              <!-- /admin,/public共通 ログアウト時のheader -->
              <% else %>
                <%= link_to homes_top_path, class: 'navbar-brand font-weight-bold pb-4' do %>
                  <%= image_tag 'logo.jpg', size: "170x30" %>
                <% end %>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav ml-auto flex-column">
                    <li class="nav-item">
                      <%= link_to reviews_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-magnifying-glass pr-2 fa-lg"></i>トピック検索
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to new_user_registration_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-user-plus pr-2 fa-lg"></i>新規登録
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to new_user_session_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fa-solid fa-right-to-bracket pr-2 fa-lg"></i>ログイン
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to homes_about_path, class: 'nav-link text-dark mr-3 my-1' do %>
                        <i class="fas fa-book-open pr-2 fa-lg"></i>About
                      <% end %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "nav-link my-1", method: :post %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </nav>
          </header>
        </div><!-- /headerのcol -->

        <div class="col-md-9 mx-auto border-left">
          <main>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
          </main>
        </div>
      </div><!-- row -->
    </div><!-- container -->
  </body>
</html>

<style>
  @media screen and (max-width: 991px){
    div.border-left {
      border-left: none !important;
    }
  }
</style>